### ISSUE TITLE
duplicate of landis hl2rp

### ISSUE THREAD

**Issue by Loucouss** [MikeWhite23/vanilla-hl2rp#1]
I think landis community got hacked as it is the exact same copy of their code client side only

best regards

**Comment by MikeWhite23** [comment]
Hello, it's vanilla code.
Not landis.

**Comment by Loucouss** [comment]
actually this code as no value, anybody connecting to a server downloads the clientsided gamemode that you uploaded here

I am sorry but without any serverside informations it is worthless
